name: PR TO DEVELOP

on:
  push:
    branches:
      - 'feat/*'
      - 'fix/*'
      - 'feature/*'

jobs:
  ci-auth-dot-net:
    uses: vyracare/vyracare-infra-pipes-dot-net/.github/workflows/ci-auth-dot-net.yml@main
    with:
      branch-name: ${{ github.ref_name }}
      project-path: "vyracare.auth.csproj"
      output-dir: "./publish"
    secrets: inherit
      
      

  open-pr-develop:
    runs-on: ubuntu-latest
    needs: ci-auth-dot-net
    if: startsWith(github.ref, 'refs/heads/feat/') || startsWith(github.ref, 'refs/heads/fix/') || startsWith(github.ref, 'refs/heads/feature/')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Open Pull Request to develop
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          source_branch: ${{ github.ref_name }}
          destination_branch: develop
          pr_title: "PR automatic ${{ github.ref_name }} into develop"
          pr_body: |
            PR automática criada pelo pipeline.
            Branch de origem: `${{ github.ref_name }}`

            name: Publish Backend
